### ISSUE TITLE
TypeError: Class constructor Document cannot be invoked without 'new'

### ISSUE THREAD

**Issue by sionnaouattara** [Luidog/marpat#22] opened 2019-10-25 16:30 UTC
Hi i'm trying to use marpat on my electron-vue project.  When i try to make a simple test of insertion in my mongo database i get this error :  

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Class constructor Document cannot be invoked without 'new'

this is package.json `content:
```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@fortawesome/vue-fontawesome": "^0.1.7",
    "@types/node": "^12.11.6",
    "admin-lte": "^3.0.0-rc.5",
    "axios": "^0.18.0",
    "bootstrap": "^4.3.1",
    "bootstrap-table": "^1.15.5",
    "bootstrap-vue": "^2.0.4",
    "font-awesome": "^4.7.0",
    "ionicons": "^4.6.3",
    "jquery": "^3.4.1",
    "marpat": "^2.1.2",
    "moment": "^2.24.0",
    "mongodb": "^3.3.3",
    "mongoose": "^5.7.7",
    "mongoose-beautiful-unique-validation": "^7.1.1",
    "nedb": "^1.8.0",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.2.20",
    "uuid": "^3.3.3",
    "validator": "^11.1.0",
    "vue": "^2.5.16",
    "vue-electron": "^1.0.6",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-electron": "^1.0.0"
  },
  "devDependencies": {
    "ajv": "^6.5.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-camo": "0.0.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "babili-webpack-plugin": "^0.1.2",
    "cfonts": "^2.1.2",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.1.6",
    "css-loader": "^3.2.0",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^2.0.4",
    "electron-builder": "^20.19.2",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "0.4.0",
    "multispinner": "^0.2.1",
    "node-loader": "^0.6.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.15.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3"
  }
```
apologize for my english, i'm french.
i need help please thank you

**Comment by Luidog** [comment] 2019-10-26 04:05
@sionnaouattara Thank you for submitting an issue. There is no need to apologize for English as a second language. I appreciate the effort you are making to communicate in my native tongue. 

As it turns out, I am can't identify the cause of the issue using the project dependencies. Would it be possible to include a stack trace of the error?

The class constructor error is thrown when a marpat document is not created using the class document's create method.

Would you mind posting an example of how you are creating and saving documents along with an error stack trace?

**Comment by sionnaouattara** [comment] 2019-10-26 20:51
@Luidog Thank you for your responding quickly. here is my insertion test marpa :

```
var connect = require('marpat').connect;
var Document = require('marpat').Document;
var database;
var uri = 'mongodb://localhost:27017/vue_electron';

class User extends Document {
    constructor() {
        super();

        this.schema({
            displayName : String,
            phoneNumber : String,
            username : String,
            password : String
        });

    }

    static collectionName() {
        return 'users';
    }
}

const state = {
    loggingIn: false,
    loginError: null,
    loginSuccessful: false
}

const actions = {
    LOGIN ({ commit }, loginData) {
        commit('LOGIN', loginData)
    },
    REGISTER ({ commit }, loginData) {
        commit('REGISTER', loginData)
    },
    DISCONNECT ({ commit }) {
        commit('DISCONNECT')
    }
}

const mutations = {
    LOGIN (state) {
        state.loggingIn = true
        console.log(state.loggingIn)
    },
    REGISTER (state, loginData) {
        console.log('test')
        state.loggingIn = true
         console.log(loginData)
        connect(uri).then(function(db) {
            database = db;
            let user = User.create()
            user.displayName = loginData.displayName
            user.phoneNumber = loginData.phoneNumber
            user.username = loginData.username
            user.password = loginData.password

            user.save().then(function() {
                console.log('User created succefully !');
            });
        });
    },
    DISCONNECT (state, errorMessage) {
        state.loggingIn = false;
        state.loginError = errorMessage;
        state.loginSuccessful = !errorMessage;
    }
}

export default {
    state,
    actions,
    mutations
}
```

and here is the error threw:

```
Login.js?37f1:7 Uncaught (in promise) TypeError: Class constructor Document cannot be invoked without 'new'
    at new User (Login.js?37f1:7)
    at Function._instantiate (D:\www\stelabdesk\node_modules\marpat\lib\base-document.js:330)
    at Function.createIndexes (D:\www\stelabdesk\node_modules\marpat\lib\document.js:368)
    at Function.create (D:\www\stelabdesk\node_modules\marpat\lib\base-document.js:311)
    at eval (Login.js?37f1:53)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
```
think you

**Comment by sionnaouattara** [comment] 2019-10-29 18:33
> @sionnaouattara Thank you for submitting an issue. There is no need to apologize for English as a second language. I appreciate the effort you are making to communicate in my native tongue.
> 
> As it turns out, I can't identify the cause of the issue using the project dependencies. Would it be possible to include a stack trace of the error?
> 
> The class constructor error is thrown when a marpat document is not created using the class document's create method. Here is an example from the tests:
> 
> https://github.com/Luidog/marpat/blob/267cc60df78c0aa2782d4eba8c81f009eb54e0e0/test/documents/document.test.js#L68-L84
> 
> If you try to create a document using the `new` constructor you would get an error similar to the one you mention.
> 
> Would you mind posting an example of how you are creating and saving documents along with an error stack trace?

@Luidog Thank you for your responding quickly. here is my insertion test marpa :

```
var connect = require('marpat').connect;
var Document = require('marpat').Document;
var database;
var uri = 'mongodb://localhost:27017/vue_electron';

class User extends Document {
    constructor() {
        super();

        this.schema({
            displayName : String,
            phoneNumber : String,
            username : String,
            password : String
        });

    }

    static collectionName() {
        return 'users';
    }
}

const state = {
    loggingIn: false,
    loginError: null,
    loginSuccessful: false
}

const actions = {
    LOGIN ({ commit }, loginData) {
        commit('LOGIN', loginData)
    },
    REGISTER ({ commit }, loginData) {
        commit('REGISTER', loginData)
    },
    DISCONNECT ({ commit }) {
        commit('DISCONNECT')
    }
}

const mutations = {
    LOGIN (state) {
        state.loggingIn = true
        console.log(state.loggingIn)
    },
    REGISTER (state, loginData) {
        console.log('test')
        state.loggingIn = true
         console.log(loginData)
        connect(uri).then(function(db) {
            database = db;
            let user = User.create()
            user.displayName = loginData.displayName
            user.phoneNumber = loginData.phoneNumber
            user.username = loginData.username
            user.password = loginData.password

            user.save().then(function() {
                console.log('User created succefully !');
            });
        });
    },
    DISCONNECT (state, errorMessage) {
        state.loggingIn = false;
        state.loginError = errorMessage;
        state.loginSuccessful = !errorMessage;
    }
}

export default {
    state,
    actions,
    mutations
}
```

and here is the error threw:

```
Login.js?37f1:7 Uncaught (in promise) TypeError: Class constructor Document cannot be invoked without 'new'
    at new User (Login.js?37f1:7)
    at Function._instantiate (D:\www\stelabdesk\node_modules\marpat\lib\base-document.js:330)
    at Function.createIndexes (D:\www\stelabdesk\node_modules\marpat\lib\document.js:368)
    at Function.create (D:\www\stelabdesk\node_modules\marpat\lib\base-document.js:311)
    at eval (Login.js?37f1:53)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
```
think you

**Comment by Luidog** [comment] 2019-10-29 22:24
@sionnaouattara I was unable to recreate this issue. The following snippet of code does create a user and log a message.

```javascript
var connect = require("marpat").connect;
var Document = require("marpat").Document;
var database;
var uri = "mongodb://localhost:27017/vue_electron";

class User extends Document {
    constructor() {
        super();

        this.schema({
            displayName: String,
            phoneNumber: String,
            username: String,
            password: String
        });
    }

    static collectionName() {
        return "users";
    }
}

connect(uri).then(function(db) {
    database = db;
    let user = User.create();
    user.displayName = "Luke Skywalker";
    user.phoneNumber = "113-8113";
    user.username = "jedi-master";
    user.password = "kenobi";

    user.save().then(function() {
        console.log("User created succefully !");
    });
});
```

I noticed that you had electron-vue as a dependency. Is it possible you are calling the create function from the (electron renderer process)[https://electronjs.org/docs/tutorial/application-architecture]? 

As it turns out, I also use marpat in an electron app. In the context of an electron integration, it is best to keep marpat on the main process only. Each renderer process can communicate to the main process via (IPC communication)[https://electronjs.org/docs/api/ipc-renderer]. 

It is possible to use marpat in a renderer process. To achieve this, you would need to add the babel presets to webpack from [this project](https://www.npmjs.com/package/babel-preset-marpat).

I am going to close this issue, but please feel free to ask any additional questions you may have. I would love to hear you were able to get this project working with electron-vue.

**Closed by Luidog** 2019-10-29 22:24 UTC
